kind: pipeline
type: docker
name: default

steps:
- name: build-linux
  image: thatcosmonaut/moonworks-build
  commands:
    - dnf install -y git cmake SDL2-devel
    - git submodule update --recursive --init
    - mkdir ./build
    - cmake -DCMAKE_C_COMPILER=/usr/bin/clang ./build
    - cd ./build
    - cmake -S .. -B .
    - make

- name: build-windows
  image: thatcosmonaut/moonworks-build
  commands:
    - dnf install -y git cmake SDL2-devel
    - git submodule update --recursive --init
    - mkdir ./build
    - cmake -DCMAKE_C_COMPILER=/usr/bin/mingw64 ./build
    - cd ./build
    - cmake -S .. -B .
    - make
