kind: pipeline
type: docker
name: default

steps:
- name: build-linux
  image: thatcosmonaut/moonworks-build
  commands:
    - dnf install -y git cmake SDL2-devel
    - git submodule update --recursive --init
    - cmake -E make_directory ./build
    - cd ./build
    - cmake -DCMAKE_C_COMPILER=/usr/bin/clang -S .. -B .
    - make

- name: build-windows
  image: thatcosmonaut/moonworks-build
  commands:
    - dnf install -y git cmake SDL2-devel
    - git submodule update --recursive --init
    - cmake -E make_directory ./build
    - cd ./build
    - cmake -DCMAKE_C_COMPILER=/usr/bin/x86_64-w64-mingw32-gcc -DMINGW -S .. -B .
    - make
