kind: pipeline
type: docker
name: default

steps:
- name: build-linux
  image: thatcosmonaut/moonworks-build:latest
  commands:
    - git submodule update --recursive --init
    - cmake -E make_directory ./build
    - cd ./build
    - cmake -DCMAKE_C_COMPILER=/usr/bin/clang -S .. -B .
    - make

- name: build-windows
  image: thatcosmonaut/moonworks-build:latest
  commands:
    - git submodule update --recursive --init
    - cmake -E make_directory ./windows-build
    - cd ./windows-build
    - mingw64-cmake -S .. -B .
    - make
